name: Auto Comment on Issue To Wait

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Comment to Issue
        run: |
          COMMENT=$(cat <<EOF
          {
            "body": "Thanks for creating the issue in WildGuard!\nBefore you start working on your PR, please make sure to:\n - ⭐ Star the repository if you haven't already.\n - Pull the latest changes to avoid any merge conflicts.\n - Attach before & after screenshots in your PR for clarity.\n- Include the issue number in your PR description for better tracking.\n  Don't forget to follow @anuragverma108 – Project Maintainer – for more updates!\n\n We're excited to see your contribution as part of Hacktoberfest 2024!  🎉  \n Happy open-source contributing!"
          }
          EOF
          )
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d "$COMMENT")
          cat response.json
          if [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to add comment"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}