name: 'Auto Assign Issue Author'

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: 'Assign issue author'
        uses: actions-ecosystem/action-assign-to-author@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'